//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual_MarkJoseph_2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.DetallePedidoes = new HashSet<DetallePedido>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<DetallePedido> DetallePedidoes { get; set; }
    }
}
